[package]
name = "slave-pool"
version = "0.3.0"
authors = ["Douman <douman@gmx.se>"]
edition = "2021"
license = "BSL-1.0"
repository = "https://github.com/DoumanAsh/slave-pool"
readme = "README.md"
description = "Simple thread pool"
keywords = ["threadpool", "thread", "threading", "parallelism"]
categories = ["concurrency"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE",
]

[dev-dependencies.thread-waker]
version = "1"
